name: Compile LaTeX PDFs

on:
  push:
    paths:
      - '**/main.tex'
  pull_request:
    paths:
      - '**/main.tex'

jobs:
  build-pdfs:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/jordanaq/texlive:latest

    steps:
      - name: Checkout repo
        uses: taiki-e/checkout-action

      - name: Detect Changed .tex files
        id: changed
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**/main.tex')
          echo "$CHANGED_FILES"
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Compile changed files
        if: steps.changed.output.files != ''
        run: |
          for file in ${{ steps.changed.outputs.files }}; do
            echo "Compiling $file"
            latexmk -lualatex -interaction=nonstopmode "$file"
          done

      - name: Upload PDFs as artifacts
        if: steps.changed.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdfs
          path: '**/main.pdf'

